### ISSUE TITLE
suggestion: features from Embbedium Extension and Embbedium Extras

### ISSUE THREAD

**Issue by mateus3c** [SrRapero720/chloride#17]
It might be worth to check the features available on these two Embbedium addons, they have a ton of optimizations and options, ut would be nice to have some on Embbedium++ considering these two are for very old versions.

https://modrinth.com/mod/embeddium-extras

https://www.curseforge.com/minecraft/mc-mods/embeddium-extension

**Comment by SrRapero720** [comment]
both mods are actually maintained, and i am aware of them, BUT all those features (except embeddium-extension, which is a fork of sodium-extras). embeddium extras doesn't have any feature than emb++ doesn't have. and emb-extension is not on my plans (because i want to take features from the original mod.
