### ISSUE TITLE
Crash trying to enter the world

### ISSUE THREAD

**Issue by qVoidreaver** [SrRapero720/chloride#21]
When I try to enter the world, Embeddium++ crashes. As I'm using a mod, the crash doesn't close my Minecraft and just notifies me which mod is the problem and, of course, points to Embeddium++. However, if I try to enter the world again, I can enter, but ALL the units are invisible.

Oh, I should also say that this doesn't happen often, when you close and open the game it may not happen at all.

[crash-2024-01-08_22.01.51-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13867683/crash-2024-01-08_22.01.51-client.txt)

**Comment by qVoidreaver** [comment]
Not in the previous version, only in the new one.

**Comment by SrRapero720** [comment]
Issue fixed, pending release for 1.2.1
Do not ask me ETA (because i am not sure when i will release this)

**Comment by Jerome226** [comment]
> Issue fixed, pending release for 1.2.1 Do not ask me ETA (because i am not sure when i will release this)

It would be nice for a quick hotfix so modpack can update without the crash.

**Comment by SrRapero720** [comment]
## FIXED IN 1.2.1 - DOWNLOAD FROM
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023086) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023094) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023095)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.1) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.1) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.1)
