### ISSUE TITLE
Dropped torch doesn't emit light whatever the settings?

### ISSUE THREAD

**Issue by AntonyCilleros** [SrRapero720/chloride#23]
I use a lot of mods so maybe embeddium+ is not the issue but dropped torches don't emit light even with everything checked on in the dynamic lights settings.
Can someone confirm this issue please?

**Comment by SrRapero720** [comment]
## FIXED IN 1.2.1 - DOWNLOAD FROM
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023086) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023094) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023095)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.1) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.1) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.1)
